name = "meowpack"
author = "masuteri"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a443c780f19d63b0326103c50e4d2505c11a540755b594d93ece112a6948a6a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.145"
