name = "meowpack"
author = "masuteri"
version = "0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c57d63acb5e05dfe033f690c5fec2adaeced5d181b12cc97bad9792fa6d40300"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.145"
