name = "meowpack"
author = "masuteri"
version = "0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a14fb2c122d9b631512ed25d99150c89a7c67bf9a73189783264593eac5c2209"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
