name = "meowpack"
author = "masuteri"
version = "0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11d493a9247fb6562d1a2a50afbb7426937dc6b4d4a2d3711711cdc66abada11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
