name = "meowpack"
author = "masuteri"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b25e536c695eee138300d15fea9c2e41432a75754de4c949e767f6e3e9d97e58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.145"
