name = "meowpack"
author = "masuteri"
version = "0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6d4a8c758e3dcfa3d2f87df433cbdc35a044ec8b9ad783886c69f46c8ca4665"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
