name = "meowpack"
author = "masuteri"
version = "0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a699ad0d4783aecf1e76e63a7d402e8d5b5516136aeb784ebd6bc6c35d9117"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
