name = "meowpack"
author = "masuteri"
version = "0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fd472498aa5559a9d12548fd7b09249c036a2af4eba5d7b950bcfc8e17f21aa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
