name = "meowpack"
author = "masuteri"
version = "0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "732d502d053e1031202da47b8ac348b47fa7854a8d4f372d853cc0d21636c5dd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.147"
